### ISSUE TITLE
저작권 관련문의

### ISSUE THREAD

**Issue by nerdchanii** [easysIT/doit_dsalgo_with_python#2]
1. 본 책을 교재로 사람들과  스터디를 진행하려고합니다. `.md` 파일로 요약정리를 하고, 해당 챕터와 관련된 알고리즘문제들을 풀어서 정리하려고합니다. 저작권에 접촉되지 않을지 문의드립니다.  레포지토리는 [nerdchanii/Algorithrm_study](https://github.com/nerdchanii/Algorithm_study)입니다.

2. 그리고 공부하는 도중에 좀 살펴보고 싶은 소스코드를 필사해서 제 TIL 레포지토리(위에와 별도의 레포지토리)에 올리고 싶은데, 
저작권 표기를 하면 괜찮은지 문의드립니다.(소스코드에 간략한 주석을 추가해서  올릴예정입니다.) 

3. 괜찮다면 저작권표기를 어떻게 해야할지 문의드립니다!

**Comment by Canine89** [comment]
네 괜찮습니다 ㅎㅎ

2021년 9월 4일 (토) 오후 2:38, nerdchanii ***@***.***>님이 작성:

**Comment by nerdchanii** [comment]
감사합니다!:) 리드미에 easysIT/doit_dsalgo_with_python 링킹해놓겠습니다:)
